version: '3.8'

services:
  client-bike:
    container_name: client-bike
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
    networks:
      - app_network
    environment:
      - CHOKIDAR_USEPOLLING=true

  server-bike:
    container_name: server-bike
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    restart: 'unless-stopped'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge